#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  7 16:19:02 2021

@author: macbook
"""

from tkinter import *
from PIL import ImageTk, Image

root = Tk()
root.title("Planet Encyclopedia")
root.geometry("500x500")
root.config(bg="lightblue")
 
colour_label = Label(root, text="Enter A Colour:")
colour_label.place(relx=0.8,rely=0.9,anchor=CENTER)

input_box = Entry(root)
input_box.insert(0,"black")
input_box.place(relx=0.8,rely=0.9,anchor=CENTER)

canvas = Canvas(root, width = 590, height=510, bg="white",highlightbackground ="lightgray" )
canvas.pack()

Img = ImageTk.PhotoImage(Image.open("ANIME .png"))
my_image = canvas.create_image(50,50,image=img)


direction = ""
oldx=50
oldy=50
newx=50
newy=50

def draw( direction,oldx,oldy, newx , newy):
    fill_colour = input_box.get()
    
    
    root.bind("<Right>",right_dir)
    root.bind("<left>",left_dir)
    root.bind("<Up>",up_dir)
    root.bind("<Down>",down_dir)

    root.mainloop()